Repository IllumiDesk/docker-stacks, pull requests merged in 2020-08, with the labels that each got.

#19 Adding Unregistered packages
  base-notebook/install.jl
Labels: julia

#20 Bump nbgrader fork and base image versions
  base-notebook/requirements.txt
  grader-notebook/Dockerfile
  instructor-notebook/Dockerfile
  learner-notebook/Dockerfile
  rstudio/Dockerfile
  theia/Dockerfile
  vscode/Dockerfile
Labels: chore

#23 Revert bower away with nbgrader fork
  base-notebook/requirements.txt
Labels: chore

#24 Use the latest base image to build the workspaces
  base-notebook/Dockerfile
  base-notebook/jupyter_notebook_config.py
  grader-notebook/Dockerfile
  instructor-notebook/Dockerfile
  learner-notebook/Dockerfile
  rstudio/Dockerfile
  theia/Dockerfile
  vscode/Dockerfile
Labels: chore

#25 adding packages
  base-notebook/install.jl
Labels: chore

#21 Consolidate role-base images
  .flake8
  .travis.yml
  Makefile
  README.md
  base-notebook/Dockerfile
  base-notebook/Manifest.toml
  base-notebook/Project.toml
  base-notebook/apt.txt
  base-notebook/environment.yml
  base-notebook/install.jl
  base-notebook/jupyter_notebook_config.py
  base-notebook/jupyter_notebook_config_base.py
  base-notebook/postBuild
  base-notebook/requirements.txt
  base-notebook/runtime.txt
  dev-requirements.txt
  grader-notebook/Dockerfile
  illumidesk-notebook/Dockerfile
  illumidesk-notebook/enable_extensions.sh
  illumidesk-notebook/global_nbgrader_config.py
  illumidesk-notebook/jupyter_notebook_config.py
  illumidesk-notebook/requirements.txt
  illumidesk-notebook/start.sh
  illumidesk-notebook/test/test_languages.py
  img/docker_stacks_v2.png
  img/grader_images.png
  img/workspace_images.png
  instructor-notebook/Dockerfile
  learner-notebook/Dockerfile
  rstudio/Dockerfile
  rstudio/jupyter_notebook_config.py
  rstudio/rserver.conf
  rstudio/test/test_rstudio.py
  theia/Dockerfile
  theia/jupyter_notebook_config.py
  theia/package.json
  theia/requirements.txt
  theia/run_theia.sh
  theia/test/test_theia.py
  vscode/Dockerfile
  vscode/jupyter_notebook_config.py
  vscode/requirements.txt
  vscode/test/test_vscode.py
Labels: refactor
