Repository IllumiDesk/docker-stacks, pull requests merged in 2020-07, with the labels that each got.

#1 First commit
  .gitignore
  .hadolint.yml
  .travis.yml
  Makefile
  README.md
  base-notebook/Dockerfile
  base-notebook/global_nbgrader_config.py
  base-notebook/jupyter_notebook_config.py
  base-notebook/requirements.txt
  grader-notebook/Dockerfile
  img/grader_images.png
  img/workspace_images.png
  instructor-notebook/Dockerfile
  learner-notebook/Dockerfile
  rstudio/Dockerfile
  rstudio/requirements.txt
  rstudio/rserver.conf
  theia/Dockerfile
  theia/package.json
  theia/requirements.txt
  theia/run_theia.sh
  vscode/Dockerfile
  vscode/requirements.txt
Labels: chore

#2 Switch to main for builds
  .travis.yml
Labels: chore

#4 Remove shell pipefail in build stage for theia image
  theia/Dockerfile
Labels: fix

#5 Ignore DL4006 with Theia Dockerfile
  .hadolint.yml
  theia/Dockerfile
Labels: chore

#6 Update Julia packages in base image
  base-notebook/Dockerfile
  base-notebook/install.jl
  base-notebook/jupyter_notebook_config.py
Labels: enhancement

#7 Add JRE and tests
  .dockerignore
  .flake8
  .gitignore
  .hadolint.yml
  .travis.yml
  Makefile
  README.md
  base-notebook/Dockerfile
  base-notebook/environment.yml
  base-notebook/global_nbgrader_config.py
  base-notebook/install.jl
  base-notebook/jupyter_notebook_config.py
  base-notebook/requirements.txt
  base-notebook/test/test_languages.py
  conftest.py
  dev-requirements.txt
  pyproject.toml
  pytest.ini
  rstudio/Dockerfile
  rstudio/requirements.txt
  rstudio/rserver.conf
  rstudio/test/test_rstudio.py
  theia/test/test_theia.py
  vscode/test/test_vscode.py
Labels: enhancement

#11 Install nbgrader only from fork
  base-notebook/requirements.txt
Labels: chore

#12 Specify v0.1.3 release tag for base image
  grader-notebook/Dockerfile
  instructor-notebook/Dockerfile
  learner-notebook/Dockerfile
  rstudio/Dockerfile
  theia/Dockerfile
  vscode/Dockerfile
Labels: chore

#13 Update illumidesk-theia-proxy version
  README.md
  base-notebook/test/test_languages.py
  theia/Dockerfile
  theia/requirements.txt
Labels: chore

#14 Update base image to v0.1.4
  grader-notebook/Dockerfile
  instructor-notebook/Dockerfile
  learner-notebook/Dockerfile
  rstudio/Dockerfile
  theia/Dockerfile
  vscode/Dockerfile
Labels: chore

#18 Adding packages
  base-notebook/install.jl
Labels: julia
