Repository IllumiDesk/docker-stacks, pull requests merged in 2021-11, with the labels that each got.

#72 Update formgradernext and async-nbgrader versions
  illumidesk-notebook/requirements.txt
Labels: dependencies

#71 updates nbextension command in dockerfile for grader-notebook
  grader-notebook/Dockerfile
Labels: bug

#73 Fix extension order
  grader-notebook/Dockerfile
  illumidesk-notebook/Dockerfile
Labels: bug

#74 add course_list extension
  grader-notebook/Dockerfile
Labels: bug

#75 Update formgradernext version
  illumidesk-notebook/requirements.txt
Labels: chore
